- README.md
- ember-addon/.jshintrc
- ember-addon/blueprints/.jshintrc
- ember-addon/blueprints/ember-data-model-fragments/index.js
- ember-addon/blueprints/fragment/files/app/__path__/__name__.js
- ember-addon/blueprints/fragment/index.js
- ember-addon/index.js
- package.json
> Add Ember CLI addon

- packages/model-fragments/lib/fragments/array/fragment.js
- packages/model-fragments/lib/fragments/attributes.js
- packages/model-fragments/tests/unit/fragment_array_test.js
- packages/model-fragments/tests/unit/fragment_test.js
- packages/model-fragments/tests/unit/polymorphic_test.js
> Fix type check problems with model factory injections

- package.json
> Added 'defaultBlueprint' override to fix lookup bug

- bower.json
> Added addon dir and other misc files to bower ignore

- packages/model-fragments/lib/fragments/array/fragment.js
- packages/model-fragments/lib/fragments/array/stateful.js
- packages/model-fragments/tests/integration/fragments/save_test.js
> Fix issue with array observer infinite recursion on adapter update

- packages/model-fragments/lib/fragments/ext.js
- packages/model-fragments/tests/integration/fragments/dependent_state.js
> Fix issue with multiple rollbacks

- package.json
> Ensure proper addon ordering (import after ember-data)

- ember-addon/blueprints/fragment/index.js
> Fixed file name in fragment blueprint when using pod structure

- packages/model-fragments/tests/integration/fragments/nested_test.js
> Add passing test case for nested fragment default values

- packages/model-fragments/lib/fragments/transform.js
> fix deprecation warnings for ember data beta 18

- packages/model-fragments/lib/fragments/attributes.js
Nice addon! Saw two typos while reading through the code.
> Fix small comment typos

- packages/model-fragments/lib/fragments/array/stateful.js
- packages/model-fragments/lib/fragments/model.js
- packages/model-fragments/tests/integration/fragments/nested_test.js
- packages/model-fragments/tests/unit/fragment_array_test.js
> Add ability to copy fragments with nested fragments

- packages/model-fragments/lib/fragments/array/fragment.js
- packages/model-fragments/lib/fragments/array/stateful.js
- packages/model-fragments/lib/fragments/ext.js
- packages/model-fragments/lib/fragments/model.js
- packages/model-fragments/tests/integration/fragments/save_test.js
> Fixed issue with fragments not being notified of change on record create

- packages/model-fragments/lib/fragments/array/fragment.js
- packages/model-fragments/lib/fragments/attributes.js
- packages/model-fragments/lib/fragments/ext.js
- packages/model-fragments/lib/util/instance-of-type.js
- packages/model-fragments/tests/integration/fragments/nested_test.js
- packages/model-fragments/tests/unit/fragments/has_many_test.js
- packages/model-fragments/tests/unit/fragments/has_one_test.js
> Add support for object literals in fragment creation and setters

- packages/model-fragments/lib/fragments/array/fragment.js
- packages/model-fragments/lib/fragments/attributes.js
- packages/model-fragments/lib/fragments/model.js
- packages/model-fragments/tests/unit/fragments/owner_test.js
> Updated fragment attrs to clear owner when releasing fragments

- packages/model-fragments/lib/fragments/array/fragment.js
- packages/model-fragments/tests/integration/fragments/save_test.js
> Actually fix issue with udpating existing fragments on create

- packages/model-fragments/lib/fragments/ext.js
- packages/model-fragments/lib/fragments/fragment.js
> Use Object.create(null) where collisions are possible

- README.md
- packages/model-fragments/lib/fragments/array/fragment.js
- packages/model-fragments/lib/fragments/attributes.js
- packages/model-fragments/lib/fragments/fragment.js
- packages/model-fragments/tests/integration/dependent_state_test.js
- packages/model-fragments/tests/integration/save_test.js
> Fixed issue with fragment property dirtiness after object literal set

- packages/model-fragments/lib/fragments/ext.js
- packages/model-fragments/tests/unit/store_test.js
> Fixed non-model serializer lookup

- packages/model-fragments/lib/fragments/ext.js
- packages/model-fragments/tests/unit/store_test.js
Fix for [#160](https://github.com/lytics/ember-data-model-fragments/issues/160)
(I suspect there is a better path to solving this issue).
> Fix for Ember Data default serializers

- packages/model-fragments/lib/fragments/array/fragment.js
- packages/model-fragments/lib/fragments/attributes.js
- packages/model-fragments/lib/fragments/fragment.js
- packages/model-fragments/tests/integration/dependent_state_test.js
> Fixed issue with fragments being dirty after store.push

- .travis.yml
No idea what the parse error actually is, but updating phantomjs to 2.x seems to solve the problem.
> Fix PhantomJS error in Travis "SyntaxError: Parse error" 

- CHANGELOG.md
- package.json
Ping: @jakesjews . Look right? If so I'll tag it, then rebase my coming `v2.11.0` release branch on top of it.
> Released v2.3.3.

- addon/ext.js
see https://github.com/lytics/ember-data-model-fragments/pull/235#issuecomment-273672169
/cc @workmanw
> detect fragment with `modelName` to avoid a deprecation warning

- addon/ext.js
Here is the upstream commit:  https://github.com/emberjs/data/commit/a5a8cd7714555655ae9fb7209b5b87c11aabd1cc 
That change was a perf improvement for ember-data, but we need to change the way we initialize our fragments to follow suite. This was pretty easy and we are able to be backwards compatible by detecting a property on the prototype. 
Let's also hold on merging this for the time being. I'd like to see the `factoryFor` PR land first. Then we can land this and all the tests should be passing.
> Fixing an Ember-Data 2.12 compatibility issue (#232).

- CHANGELOG.md
- package.json
Ping @jakesjews . Everything look right here?
> Released v2.11.1

- addon/ext.js
> Fixed `modelFactoryFor` bug. 

- README.md
Feditor's URL changed to http://feditor.tech
> Update Feditor URL

- addon/ext.js
- addon/states.js
- tests/integration/components/alias-component-test.js
Resolves https://github.com/lytics/ember-data-model-fragments/issues/259 but removes fix for https://github.com/lytics/ember-data-model-fragments/issues/190
> revert fix-infinite-changed-key-loop

- addon/ext.js
- tests/dummy/app/models/name.js
- tests/unit/fragment_test.js
Howdy, this relates the the issue #250
> fragments invoke ready callback when they are created

- .travis.yml
- README.md
- addon/ext.js
- addon/states.js
- addon/util/instance-of-type.js
- config/ember-try.js
- package.json
- tests/unit/fragment_test.js
Not quite ready to merge. Still waiting on: https://github.com/emberjs/data/pull/5008 to make it into beta. 
This is mostly ready. Need to wait for ember-2.14.0 to be released. Then I'll squash it all and submit for review.
> WIP ember-data-model-fragments-2.14

- addon/fragment.js
Fixes https://github.com/lytics/ember-data-model-fragments/issues/290
> Fix ember-data 3.x compability

- addon/attributes.js
- tests/unit/fragment_property_test.js
Fixes https://github.com/lytics/ember-data-model-fragments/issues/306
EDIT: I'll add a test soon
> Fix bug where setting array fragment attr to null can cause error

- addon/ext.js
- tests/unit/fragment_test.js
> Return an array with the diff in changedAttributes

- addon/ext.js
> fix: use send('loadedData') instead of loadedData method

- addon/transforms/fragment-array.js
- addon/transforms/fragment.js
This PR has not been tested yet !
> fix(serialize): fix serialization in ember 3.28

- index.js
> Remove bowerDependencies warning

- addon/ext.js
- addon/record-data.js
- tests/helpers/start-app.js
- Fixes Ember 4 deprecation warning https://deprecations.emberjs.com/v4.x/#toc_ember-polyfills-deprecate-assign
> Remove assign usage

- types/registries/fragment.d.ts
> Remove string index from fragment registry

- README.md
> Convert README.md examples to native classes

- addon/record-data.js
- tests/integration/render_test.js
I identified [this code as problematic](https://github.com/adopted-ember-addons/ember-data-model-fragments/issues/467#issuecomment-1624297238) previously, but the tests passed without it so [a partial fix was merged](https://github.com/adopted-ember-addons/ember-data-model-fragments/pull/469). More tests are needed! This would fix #467.
> Ensure changing arrays are notified.

- addon/record-data.js
- tests/unit/serialize_test.js
Will also:
- fix adopted-ember-addons/ember-data-model-fragments#470
> fix(polymorphism): fix regression introduced with ember-data-model-fragments 6.0.0 where owner is not passed to typeKey function

- fragment.d.ts
- [Defined here](https://github.com/adopted-ember-addons/ember-data-model-fragments/blob/11e263b11c911a23c430db8bd2b77a1f40eef68c/addon/fragment.js#L91)
> Add `copy` to type declarations
