- packages/model-fragments/lib/fragments/attributes.js
- packages/model-fragments/tests/integration/fragments/save_test.js
Currently in certain annoying cases in Ember, including aliases or proxies that are actively observed,
CPs are consumed as soon as they are changed. This used to cause an infinite loop. For example:
If you had
```
App.User = DS.Model.extend({
name: hasOneFragment('name')
})
App.Name = DS.ModelFragment.extend({
firstName: DS.attr()
})
```
1. We would push new data for a user
2. We would notify a change for the user.name which cleared the fragments cache
3. An observer would try to get `user.name.firstName` synchronously
4. As we had new data, we would try to setupData on the fragment
5. In the middle of fragment data setup we would notify a change to `firstName`
6. The observer would fire immediately and try to get `user.name.firstName` even though
we weren't done with the setup
7. Goto 4 …
> Fix infinite loops when reloading observed fragments

- bower.json
- packages/model-fragments/lib/core-model.js
- packages/model-fragments/lib/fragments/array/fragment.js
- packages/model-fragments/lib/fragments/array/stateful.js
- packages/model-fragments/lib/fragments/ext.js
- packages/model-fragments/lib/fragments/transform.js
- packages/model-fragments/lib/snapshot.js
- packages/model-fragments/tests/unit/fragment_test.js
- test.html.mustache
The change to passing snapshots to serializers instead of records has interesting implications for model fragments. At their core, fragments are simply embedded JSON attributes, so from the perspective of a snapshot, they should be considered attributes and _not_ relationships. The `hasOneFragment` and `hasManyFragments` properties are already marked as attributes, but when creating a new snapshot, the fragment model/array instance is returned when calling `snapshot#attr` – not exactly a snapshot of the attributes.
Therefore fragments need to be serialized in the snapshot _before_ `DS.Model#serialize` is invoked, instead of afterwards when transforms are applied to attributes. This unfortunately means relying on even more private APIs, in this case `DS.Model#_createSnapshot` (since the …
> Snapshot update (beta.15 compatibility)

- index.js
- package.json
Addon discovery now relies on the addon name being exported, see https://github.com/ember-cli/ember-cli/pull/3335
> Added ember-cli addon main file to support v0.2.0

- ember-addon/app/transforms/fragment.js
This allows the normal resolver to find `transform:fragment` when using `moduleForModel` either with `needs: [ 'transform:fragment' ]` or with `integration: true`.
Fixes https://github.com/lytics/ember-data.model-fragments/issues/80.
Fixes https://github.com/lytics/ember-data.model-fragments/pull/87.
> Allow easier unit/integration testing from ember-cli.

- packages/model-fragments/lib/fragments/ext.js
Since Ember 2.1 `registry` is public.
See emberjs/ember.js#11440.
Closes #141
> Use public registry.

- packages/model-fragments/lib/fragments/attributes.js
- packages/model-fragments/tests/unit/default_value_test.js
- packages/model-fragments/tests/unit/fragments/has_many_test.js
- packages/model-fragments/tests/unit/fragments/has_one_test.js
Fixes #138.  Added some basic `defaultValue` tests as well.
Once this is merged into master, I'll rebase #127, and hopefully we can get that one in too.
> Established values are no longer clobbered by defaultValue

- README.md
- packages/model-fragments/lib/fragments/ext.js
- packages/model-fragments/tests/unit/store_test.js
Closes #135
This changes the behavior of `store.serializerFor` to skip `serializer:application` and the default adapter's `defaultSerializer` property. It will also use `serializer:-fragment` if registered as a convenience for apps that want a serializer that is different from the application serializer, but do not want to create a boilerplate serializer class for every fragment class. Prefixing it with a dash requires devs to register it in a custom initializer, but it avoids potential naming clashes.
This is a breaking change since many apps may rely on using the application serializer as the default fragment serializer, and will be part of the 1.0 release.
cc @dfreeman
> Changed default fragment serializer to use store default

- packages/model-fragments/lib/fragments/array/fragment.js
- packages/model-fragments/lib/fragments/attributes.js
- packages/model-fragments/lib/fragments/fragment.js
- packages/model-fragments/tests/integration/dependent_state_test.js
- packages/model-fragments/tests/unit/fragment_owner_property_test.js
This reverts the behavior described in #133. It turns out there was a very good reason for only ever allowing a fragment to belong to one owner: it prevents conflicts when rolling back a record with fragments:
```js
var fragment = record1.get('fragment');
record1.set('fragment', null); // Previously, this cleared the fragment's owner
record2.set('fragment', fragment); // Possible, since the fragment has no owner
record1.rollback();
fragment.get('owner'); // ???
```
this is a breaking change for anyone that has upgraded to v0.4.2 or v0.4.3 and now relies on this behavior. However, since chances of that are small, and this was an oversight on my part and introduces a bug, this should be treated as like a bugfix (no minor version number bump).
@martinthogersen I'm curious if you've updated …
> Revert fragment owner reseting

- packages/model-fragments/lib/fragments/array/fragment.js
- packages/model-fragments/lib/fragments/ext.js
- packages/model-fragments/tests/integration/nested_test.js
- packages/model-fragments/tests/unit/fragment_array_property_test.js
- packages/model-fragments/tests/unit/fragment_property_test.js
- packages/model-fragments/tests/unit/fragment_test.js
- packages/model-fragments/tests/unit/store_test.js
I tracked down a memory leak since my acceptance tests started running the process out of memory. This is from a heap snapshot showing the ember `Container` instance being rooted in `window`:
```
container in Class @8620175
_object in ChainNode @8620223
_parent in ChainNode @8614719
[2] in Array @8610299
isDirty in EmptyObject @8607285
chains in ChainWatchers @8601471
_chainWatchers in Meta @8065411
__ember_meta__ in @7311237
saved in @8042657
loaded in @8042653
model$fragments$lib$fragments$states$$default in system / Context @8042649
context in model$fragments$lib$fragments$attributes$$fragmentArray() @8042947
fragmentArray in Class @7447369
MF in Window
```
I had about as many containers rooted as the number of acceptance tests.
The leak happens because `window.MF` has the …
> Fix memory leak caused by fragments not being destroyed

- packages/model-fragments/lib/fragments/array/fragment.js
- packages/model-fragments/lib/fragments/array/stateful.js
- packages/model-fragments/lib/fragments/ext.js
- packages/model-fragments/lib/fragments/fragment.js
- packages/model-fragments/tests/integration/save_test.js
This PR is intended to fix #177. It ensures adapter errors are properly handled.
There are some open questions here and I would like @slindberg to weigh in when he is able to. 
One question is should the fragments call `internalModelFor(this)._saveWasRejected()` instead of `    internalModelFor(this).adapterDidError(error);`? The challenge I discovered was that the internal-model's [adapterDidError](https://github.com/emberjs/data/blob/266ae624a6005092f7e3758005920039081b8884/addon/-private/system/model/internal-model.js#L735-L743) ultimately tries to call `this.send('becameError');`. However since the fragment never enters the inFlight state, that `becomeError` isn't a valid action. 
Second question, what does it mean for a fragment to be in "error"? I passed the error object for the …
> Fixing #177. Ensures that adapter errors are properly handled.

- bower.json
With the current version strategy in bower.json, this addon will install 2.4.1 and therefore tests will fail in master.
Now it will stay in 2.2.X.
> Lock ember-data to supported version

- packages/model-fragments/lib/fragments/states.js
- packages/model-fragments/tests/integration/save_test.js
- packages/model-fragments/tests/unit/fragment_test.js
Fixes #159 
@workmanw I'm thinking I just left this out when initially creating the state machine, but I wanted a gut check from you. There's no deleted state for a fragment, but there is a new state, and I don't think there's any harm in reporting it as 'isNew'.
> Fixed issue with 'isNew' for newly created fragments

- README.md
I'm submitting this as a PR to the addonify branch so that @slindberg and @jakesjews can review it. Here is a link to the [rendered view](https://github.com/workmanw/ember-data-model-fragments/blob/d15613cf9d62c30e604dc08d5031adeddc7e975a/README.md).
There are two things I specifically wanted to get feedback on. 
1. Since I've upgraded the docs to use the newish ES6 model pattern (rather than globals) the examples tend to have more files. See [here](https://github.com/workmanw/ember-data-model-fragments/blob/d15613cf9d62c30e604dc08d5031adeddc7e975a/README.md#example). I added the name of the model as a path based code comment at the top of each snippet. This is what many addons do, include the official ember model guides. My question is, is that clear enough for someone reading it? If …
> First pass at updating the README.md to match the new addonify patterns.

- addon/fragment.js
- bower.json
- package.json
- tests/helpers/start-app.js
Replace deprecated use of Ember.merge with Ember.assign.
Right now an assertion is being triggered in ember-data since Ember.merge is being used and this is causing a null exception in toString() since it's called before the owner is set. It seems like there could be other cases where toString could be called before a parent is assigned so this might be a useful fix.
> ember 2.5 compatibility

- README.md
I thought it would be useful to add a how-to for registering the `serializer:-fragment` in an initializer. I had to go off and learn how to do this so may be handy to have it available at the point in the documentation where it's mentioned.
> Add custom serializer how-to to README.

- tests/unit/fragment_array_test.js
Use `includes` instead of `contains` when possible. Beginning in Ember 2.8 `contains` is deprecated and will produce a deprecation warning.
> Fixing tests with ember-2.9

- README.md
The example did not work for me without this patch. (tried with Ember(Data) 2.7 and 2.8).
Perhaps I did it [incorrect](https://github.com/lytics/ember-data-model-fragments/issues/213) but I found that the following method could never work as the `data` argument did not contain the typeKey's field.
https://github.com/lytics/ember-data-model-fragments/blob/master/addon/fragment.js#L160
```
export function getActualFragmentType(declaredType, options, data) {
console.log(declaredType, options, data); // would log: normalize Object {name: "Leonard", hasManes: true}
if (!options.polymorphic || !data) {
return declaredType;
}
var typeKey = options.typeKey || 'type';
var actualType = data[typeKey];
return actualType || declaredType;
}
```
> updates polymorphisme example

- addon/fragment.js
When using mixed adapters sometimes `internalModel` is null and an error is thrown. This PR checks to see if internalModel is set so that the `toStringExtension` doesn't fail.
> Fix `internalModel is null` error in `toStringExtension`

- addon/states.js
`Ember.K` has been deprecated and will be removed in 3.0, so it's time to remove it here too.
> Remove deprecated Ember.K

- addon/ext.js
- tests/unit/store_test.js
[`ember-data-factory-guy`](https://github.com/danielspaniel/ember-data-factory-guy) currently relies on [`store.createFragment` raising an exception](https://github.com/danielspaniel/ember-data-factory-guy/blob/20ba57cafaa366b59e62fd9e1afef01d5d673c53/addon/model-definition.js#L41-L50) to detect if a model is a factory. This exception comes from an assertion which will be stripped in certain builds once https://github.com/ember-cli/rfcs/pull/50 is adopted.
This PR introduces a `store.isFragment` method which will allow ember-data-factory-guy to do something like:
```js
isModelAFragment() {
if(FactoryGuy.store.isFragment) {
return FactoryGuy.store.isFragment(this.modelName);
}
return false;
}
```
There are currently failing tests on master, and the same on this branch. …
> Added `store.isFragment`

- .travis.yml
- README.md
- addon/ext.js
- bower.json
- config/ember-try.js
- package.json
Adding support for Ember-Data 2.11. Fixing #224. Unfortunately this change is not going to be backwards compatible with `>= ember-data v2-10.x`.
**This is still WIP. DO NOT MERGE** 😄. My plan is to merge this after Ember-Data 2.11.0 ships.
------------
Just leaving some notes here so I can remember in 4-5 weeks 😜 .
TODOs -- Once Ember-Data `2.11.0` ships:
> [WIP] Adding support for ember-data 2.11.

- addon/ext.js
Let's hold on merging this until after Ember-Data's change lands in their beta channel. See: https://github.com/emberjs/data/pull/4743 .
> [WIP] Removes deprecation from upcoming Ember 2.12 release.

- .travis.yml
- README.md
- addon/array/fragment.js
- addon/array/stateful.js
- addon/attributes.js
- addon/ext.js
- addon/fragment.js
- addon/index.js
- addon/states.js
- addon/transforms/array.js
- addon/transforms/fragment-array.js
- addon/transforms/fragment.js
- addon/util/map.js
- app/initializers/model-fragments.js
- config/ember-try.js
- tests/helpers/setup-ember-dev.js
- tests/integration/app_test.js
- tests/integration/dependent_state_test.js
- tests/integration/nested_test.js
- tests/integration/save_test.js
- tests/unit/array_property_test.js
- tests/unit/deprecation_test.js
- tests/unit/fragment_array_property_test.js
- tests/unit/fragment_array_test.js
- tests/unit/fragment_owner_property_test.js
- tests/unit/fragment_property_test.js
- tests/unit/fragment_test.js
- tests/unit/polymorphic_test.js
- tests/unit/serialize_test.js
- tests/unit/store_test.js
- Skipped the tests package because there were a LOT of double quote strings and I didn't want to make this review worse. 
I know this is a big PR to review. No rush, do it when you have time. I separated various topics into separate commits incase there was something we wanted to backout. My plan is to squash them all down into a single ES6 commit. Let me know what you think, happy to change anything add or remove stuff.
My motivation was to:
1. Get the code style more consistent (we had been writing ES6 stuff as new PRs were merged, but we still had a lot of ES5 stuff from the old'n days). 
2. Install ESLint and get a sane configuration (more on that to come in a future PR).
> ES6-ify this addon.

- README.md
- app/initializers/model-fragments.js
- app/transforms/array.js
- app/transforms/fragment-array.js
- app/transforms/fragment.js
- blueprints/fragment/files/app/__path__/__name__.js
- index.js
- tests/dummy/app/models/address.js
- tests/dummy/app/models/animal.js
- tests/dummy/app/models/hobby.js
- tests/dummy/app/models/house.js
- tests/dummy/app/models/info.js
- tests/dummy/app/models/name.js
- tests/dummy/app/models/order.js
- tests/dummy/app/models/person.js
- tests/dummy/app/models/product.js
- tests/dummy/app/models/user.js
- tests/dummy/app/models/zoo.js
- tests/integration/nested_test.js
- tests/integration/save_test.js
- tests/unit/array_property_test.js
- tests/unit/fragment_array_property_test.js
- tests/unit/fragment_owner_property_test.js
- tests/unit/fragment_property_test.js
- tests/unit/model_fragments_module_test.js
- tests/unit/serialize_test.js
- vendor/model-fragments-shim.js
Unfortunately this requires use to change the module name of this addon from `model-fragments` to `ember-data-model-fragments`. Added a vendor shim to provide backwards compatibility.
See: #245. 
Two outstanding questions:
1. Are there any other implications here? _I can't think of any, it should just work._
2. Should we deprecate using `model-fragments` right away or wait a while?
> Fixing issue #245. 

- addon/ext.js
- addon/states.js
- package.json
- tests/dummy/app/components/alias-component.js
- tests/dummy/app/models/passenger.js
- tests/dummy/app/models/vehicle.js
- tests/dummy/app/templates/components/alias-component.hbs
- tests/integration/components/alias-component-test.js
Possible fix for #190.
Borrowed from repo @DingoEatingFuzz wrote to illustrate the bug to write a failing test. The issue as far as we could tell seemed to result from infinite recursion from always generating false-positives when checking what keys changed. Since the model's `_attributes` assigned in `states.js` L173 was the fragment's `InternalModel`, the `isEqual` comparison to the Object returned from the server in Ember Data's `_changedKeys` method would always be false, and thus the key would endlessly be returned to be passed along to observers watching for a change ... which would cause them to call `setupData`, which would call `_changedKeys`, etc. The combination of assigning the updated data to `_attributes` and then filtering `_changedKeys` based on whether the returned …
> Fix for Max Call Stack Size Exceeded error when using multiple aliases

- addon/ext.js
- tests/dummy/app/models/zoo.js
- tests/unit/fragment_test.js
Fixes #261.
Comment explains it all: https://github.com/lytics/ember-data-model-fragments/issues/261#issuecomment-299482222 . TL;DR; ember-data has a new lifecycle for `internalModel`s with a loaded relationship. We have to do a better job cleaning up.
> Make sure fragments are properly cleaned up when a model is unloaded.

- index.js
- package.json
This implements the `cacheKeyForTree` as outlined in [this RFC](https://github.com/ember-cli/rfcs/blob/master/complete/0090-addon-tree-caching.md).
See [Ember Data#5110](https://github.com/emberjs/data/pull/5110) for a more detailed explanation.
> Add cacheKeyForTree

- tests/unit/array_property_test.js
Was just going over my merged PR https://github.com/lytics/ember-data-model-fragments/pull/286 and realised one of my tests and 2 others already in the code were passing even though they shouldn't have been.
They were using `assert.ok` when they should have been `assert.equal`
> Fixed some tests

- addon/ext.js
The `getRecords` function inside Ember Data treats attributes
differently.
Where once the it would set each attribute on the internal model with
`options[]=` (triggering the setter/getter we install to properly
install EDMF) it now calls `InternalModel#setDirtyAttribute`.
The deciding factor for whether something is an `attribute` was based
off the `meta` set on the installed CP's.  We're instead telling the
`InternalModel#fields` function to properly recognize fragments as
`"fragments"` which bypasses the `setDirtyAttribute` call and instead
does the default behavior from before.
Reopening the Model in this way preserves the previous behavior.
I suspect, this will likely need a large refactor when RFC293 lands
https://github.com/igorT/rfcs/blob/17e8f97049452ae18d3b12ee23c4858a6d5e0bfd/tex …
> Fix EDMF for use with >3.2

- README.md
Probably a good idea before people start upgrading to Ember 3.5 thinking that EDMF will work with it based on what the readme currently says
> Update README.md to mention Ember 3.5 changes

- addon/record-data.js
- tests/integration/dependent_state_test.js
- Changing a fragment
- Then changing a property
- And finally resetting the property to its old value
`hasDirtyAttributes` should be `true`
`hasDirtyAttributes` is `false`
> fix(hasDirtyAttributes): fix hasDirtyAttributes when resetting a property

- addon/record-data.js
We're having some failing tests with ember+ember-data @ 3.28 due to missing model errors.
These args seem to be necessary if I'm correct https://github.com/emberjs/data/blob/9889ebbd4eec162dba17bb00126ee71e49d04bce/packages/record-data/addon/-private/record-data.ts#L361
> Pass arguments to `super.commitWasRejected` to get back `DS.Errors`

- addon/ext.js
- tests/integration/save_test.js
Steps to reproduce:
1. Modify a fragment attribute and save
2. The server returns a different value for the attribute in its response
**Expected:** the fragment attribute should have the new value from the server (consistent with regular ED attributes outside of fragments)
**Actual:** the fragment attribute still has the locally modified value
The root cause seems to be `willCommit` not being called for fragments. `willCommit` is normally responsible for moving `_attributes` into `_inFlightAttributes`:
https://github.com/emberjs/data/blob/f56b22c4d6eefab8915ca48979f7d813f612971d/packages/record-data/addon/-private/record-data.ts#L120-L123
This is important because `_changedKeys` prefers to take `_attributes` over attributes in the response body: …
> Fix fragment attributes in save response being ignored

- .github/workflows/ci.yml
- README.md
- config/ember-try.js
@knownasilya Any thoughts on this?
Until https://github.com/adopted-ember-addons/ember-data-model-fragments/issues/406 is resolved CI is 🔴. Should we disable testing against Ember Data release until we land a fix there? It will remove noise on any PRs we land in the meantime. I think we should continue testing against ember-source release though
I've also added a note to the README about 3.28 not being fully supported yet
Edit: I've changed to opt out of ember-release altogether as lots of changes are required to make the test suite run in ember 4.0
> Do not fail CI on Ember release

- addon/record-data.js
- tests/unit/fragment_array_test.js
- tests/unit/fragment_test.js
Prior to this change, if a `fragment` was initialized with some value, and then server responds with a `null` it did not have any impact on a fragment state, and it kept having a non-empty value assigned. Now it's fixed, so the fragment attribute can be updated to `null`.
The same behavior is applied to the `fragmentArray`. Technically, this is a *breaking change*, since before, if non empty
`fragmentArray` received a `null` from the server, instead of nullifying the attribute, the `fragmentArray` instance just
became empty(with no items inside).
It was misaligned with how the `fragmentArray` handles `null` on create, cause during creation it is nullable. So for consistency, we let it be nullable on updates as well.
> [breaking][bugfix] respect null on server updates 

- addon/record-data.js
- tests/dummy/app/models/name.js
- tests/dummy/app/models/prefix.js
- tests/unit/fragment_array_test.js
- tests/unit/fragment_test.js
- tests/unit/serialize_test.js
This is a failing test which mimics the bug in https://github.com/lytics/ember-data-model-fragments/issues/375. This worked before the 5.0.0 beta.
I originally commented most of this in https://github.com/adopted-ember-addons/ember-data-model-fragments/issues/375#issuecomment-940076666. Essentially if you have a model/fragment which has a fragment array/fragment property set to `null` it will never update when a http response has those properties updated. I have confirmed running these failing tests on a v4 branch pass just fine.
I've tracked the bug down to the following lines of code in the `FragmentRecordData#didCommit` hook:
https://github.com/adopted-ember-addons/ember-data-model-fragments/blob/4f77b2d5ea08685230ec60b5a3ddd2b3d3a7ec6c/addon/record-data.js#L426-L433
Basically because …
> Make sure we can update fragments/fragment arrays after they are initially set to null

- CHANGELOG.md
- RELEASE.md
- package.json
- yarn.lock
Fixes https://github.com/adopted-ember-addons/ember-data-model-fragments/issues/420
Adopted Ember Addon org guidelines are that repos should [automate their release process using release-it](https://github.com/adopted-ember-addons/program-guidelines#release-process). This was also pointed out in #420 where it was noted we were missing some entries from `CHANGELOG.md`.
* Adds `release-it` and `release-it-lerna-changelog` as `devDependencies`
* Adds `RELEASE.md` with release process information, automated from [`create-rwjblue-release-it-setup`](https://github.com/rwjblue/create-rwjblue-release-it-setup)
* Updates `CHANGELOG.md` with the two missing releases. This was done manually as we'd already created entries for those releases.
> Add `release-it` to automate releases and add missing entries from CHANGELOG.md

- README.md
- addon/fragment.js
This PR enables the following:
```js
export default class Monster extends Model {
@attr('string') monsterType;
@fragment('characteristic', { polymorphic: true, typeKey: (data, owner) => `${owner.monsterType}-characteristics` })
characteristics;
@fragmentArray('quality', { polymorphic: true, typeKey: (data, owner) => `${data.qualityType}-quality` })
qualities;
});
```
> feat(polymorphism): add the possibility to compute the type based on owner and data

- addon/ext.js
- tests/integration/save_test.js
This commit: https://github.com/adopted-ember-addons/ember-data-model-fragments/commit/f64a15ed57671923e7f630c9a5277541ea506bd4 introduced an issue on the dirty state. The attribute `_data` was always overridden even if the server does not send any data. 
This means that whenever you get a 204, the current state was `_data = {}` (an empty json). So whenever we try to update a property even to the same value the record is marked as dirty and the `changedAttributes` old value was always `undefined`
> fix(dirty state): prevent record from being tagged as dirty when not changed

- addon/ext.js
- tests/dummy/app/models/component-options-chart.js
- tests/integration/save_test.js
Some code was not updated. It seems `_fragments` has been replaced by `fragments` property but in some places we still use `_fragments`. The thing is when didCommit is called it use the `_fragments` to notify the nested attributes they were not dirty anymore
> fix(dirty state): fix dirtyness after save when using polymorphic fragment in some specific use case

- addon/ext.js
- addon/record-data.js
- tests/unit/fragment_test.js
Updating a fragment to something that should be another fragment type doesn't work. I just make sure that when setting a fragment value the type is the same otherwise recreate the fragment
> fix(polymorphic): update of type of a polymorphic key works

- README.md
- attributes.d.ts
- ext.d.ts
- types/registries/fragment-attributes.d.ts
This PR fixes some type string vs type class inconsistencies in the TypeScript declaration files from #443 
#444
> chore: fix typescript declarations

- addon/ext.js
- Avoid `trigger` error on Ember >= 4.x
```error
Uncaught (in promise) TypeError: fragment.trigger is not a function
at StoreService.createFragment (ext.js:182:1)
at createFragment (fragment.js:198:1)
at FragmentRecordData.setupFragment (record-data.js:56:1)
at FragmentRecordData.getFragment (record-data.js:65:1)
at ManagedRiskTagModel.get (attributes.js:177:1)
at index.js:1329:1
at untrack (validator.js:648:1)
at ComputedProperty.get (index.js:1328:1)
at ManagedRiskTagModel.getter [as title] (index.js:893:1)
at getPossibleMandatoryProxyValue (index.js:1720:1)
```
> Fix: trigger error on Ember >= 4.x

- .github/workflows/ci.yml
- README.md
- config/ember-try.js
- package.json
- tests/dummy/config/targets.js
- yarn.lock
Deps require node 14, specifically @embroider/utils.
Update auto-import.
Makes Ember 4.4 lts optional for ci (it fails for now)
> chore: drop node 12

- addon/array/stateful.js
- addon/attributes/array.js
- addon/attributes/fragment-array.js
- tests/integration/render_test.js
Fixes https://github.com/adopted-ember-addons/ember-data-model-fragments/issues/357
Constructing a record throws an error:
```js
store.createRecord('person', {
titles: ['Hand of the King', 'Master of Coin'],
});
```
```
Error: Assertion Failed: You attempted to update `[]` on `<(unknown):ember176:owner(null)>`, but it had already been used previously in the same computation.  Attempting to update a value after using it in a computation can cause logical errors, infinite revalidation bugs, and performance issues, and is not supported.
`[]` was first used:
- While rendering:
-top-level
application
index
PersonComponent
Stack trace for the update:
at dirtyTagFor (http://localhost:4201/assets/vendor.js:49934:37)
at markObjectAsDirty (http://localhost:4201/assets/vendor.js:9751:32)
at …
```
> Fix glimmer render error when creating fragment arrays

- addon/record-data.js
- tests/integration/save_test.js
I was looking at getting [reloading for fragment arrays working](https://github.com/adopted-ember-addons/ember-data-model-fragments/issues/467), and I think I stumbled across a bug.
This conditional:
```
if ((updates[key] === null) !== (original[key] === null))
```
it wasn't catching when the array existed and was different, so I added another condition `(updates[key] !== original[key])`. This updated the `_fragmentData` properly, but the cache was still being used so updates weren't making it through. I nabbed some code to clear the cache and the test started passing.
> Fix issue with reloading array records.

- addon/record-data.js
- tests/dummy/app/models/component.js
- tests/dummy/app/serializers/component.js
- tests/unit/serialize_test.js
When trying to upgrade to the latest version of ember-data-model-fragments I realised there was an issue inside the `changedAttributes()`. 
`changedAttributes()` is supposed to return all the dirty attributes until the record has been fully committed not just when calling the `save` method
In the test I show what we do, we use it to send only the dirty attributes
> changedAttributes still return the dirty attributes until the record has been fully committed

- .github/workflows/ci.yml
- addon/record-data.js
- tests/dummy/config/ember-try.js
I realised we had an issue on, that I reproduce pretty easily in my app with Ember-data 4.6. 
The RecordState is registered when we create a new Model.
For a classic native model, the RecordState will be build after all the initial value of the attributes have been set.
But with fragments it's the opposite, the RecordState is build first then the attributes are set which result in a duplicate update of the state
This produce the exact same error that you can find on this issue: https://github.com/adopted-ember-addons/ember-data-model-fragments/issues/427
My fix is based on the RecordDataDefault, I saw they are using `notifyPropertyChange` to notify an attribute has change instead of what we are doing which is using notifyStateChange to say the state of the record has changed
> fix: prevent You attempted to update _tracking on Tag issue on Ember-data 4.5+

- tests/integration/save_test.js
Previously these tests simulate an error response with pretender's catchall unhandled request:
```
Error: Pretender intercepted PUT /people/1 but no handler was defined for this type of request
at Pretender.unhandledRequest (pretender.es.js:297:1595)
at Pretender.handleRequest (pretender.es.js:297:263)
at FakeRequest.send (pretender.es.js:284:496)
at eval (pretender.es.js:264:85)
at new Promise (<anonymous>)
at fetch (pretender.es.js:263:1705)
at ApplicationAdapter._fetchRequest (rest.js:943:1)
at ApplicationAdapter.ajax (rest.js:908:1)
at ApplicationAdapter.updateRecord (rest.js:701:1)
at -private.js:1022:1
```
This is annoying because it trips the debugger's uncaught exception breakpoint.
> use explicit error responses in tests

- .github/workflows/ci.yml
The library is not currently expected to work on Ember 4.8. See https://github.com/adopted-ember-addons/ember-data-model-fragments/issues/471
> allow test failures for Ember 4.8

- addon/array/fragment.js
- tests/unit/fragment_array_property_test.js
- tests/unit/fragment_property_test.js
When calling `createRecord` or `createFragment`, it's possible to pass arbitrary extra props which are not defined on the model. #483 broke this behavior when calling `fragmentArray.createFragment(props)`
> fix passing arbitrary props to `fragmentArray.createFragment`

- .github/workflows/ci.yml
- addon/array/stateful.js
- package.json
- tests/helpers/assertion.js
- tests/test-helper.js
- tests/unit/fragment_array_property_test.js
- tests/unit/fragment_owner_property_test.js
- tests/unit/fragment_property_test.js
- tests/unit/polymorphic_test.js
- tests/unit/store_test.js
- yarn.lock
In production builds, certain fragment array mutations produce the wrong result. For example, this code swaps the first two items in the array:
```js
const first = fragmentArray.objectAt(0)
fragmentArray.removeAt(0)
fragmentArray.insertAt(1, first)
```
In development, this works as expected. But in a production build, this code results in the first item being duplicated (as if the `removeAt` did not happen).
There are already some failing tests for this issue, as long as we run the tests in production mode:
```
not ok 19 Chrome 124.0 - [23 ms] - integration - Dependent State: reordering a fragment array dirties the fragment array and owner record
---
actual: >
3
expected: >
2
stack: >
at Object.<anonymous> (http://localhost:7357/assets/tests-28c38f66d4715374e954e49f4d4e8a30.js:39:22) …
```
> Fix updating fragment arrays multiple times in the same runloop

- addon/array/fragment.js
- addon/array/stateful.js
- addon/record-data.js
- tests/integration/render_test.js
- tests/unit/array_property_test.js
- tests/unit/fragment_array_property_test.js
- tests/unit/fragment_property_test.js
When unloading a record, ember-data's `@attr`, `@belongsTo` and `@hasMany` preserve the record's most recent state, even though the underlying `RecordData` has been reset.
This project's `@fragment` and `@array` also work this way, but there's a problem with `@fragmentArray`.
Consider this component using the [order](https://github.com/adopted-ember-addons/ember-data-model-fragments/blob/master/tests/dummy/app/models/order.js) and [product](https://github.com/adopted-ember-addons/ember-data-model-fragments/blob/master/tests/dummy/app/models/product.js) models from this project's test suite:
```gjs
import Component from '@glimmer/component';
import { service } from '@ember/service';
import { action } from '@ember/object';
export default class OrderComponent extends Component {
@service …
```
> Preserve fragment array state after the record is unloaded
